version: 2 # use CircleCI 2.0
jobs: # basic units of work in a run
  build: #  must have a `build` job as entry point
    docker: # run the steps with Docker
      - image: cimg/go:1.17
      - image: cimg/postgres:14.0.0
        environment: # environmental variables for container
          POSTGRES_USERNAME: postgres
          POSTGRES_DBNAME: userdata

    working_directory: ~/usr/src/app   # Go module is used, so we dont need to worry about GOPATH

    steps: # steps that comprise the `build` job
      - checkout # check out source code to working directory
      - run:
          name: "get dependencies"
          command: cd src && go mod download


      #  Wait for mysql to be ready before proceeding
      - run:
          name: Waiting for mysql to be ready
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Run unit tests
          command: cd src && go test -v ./...  # our test is inside the "tests" folder, so target only that

workflows:
  version: 2
  build-workflow:
    jobs:
      - build